const ManageUserInfoActionsTypes = {
  UPDATE_USER_DETAILS_START: 'UPDATE_USER_DETAILS_START',
  UPDATE_USER_DETAILS_SUCCESS: 'UPDATE_USER_DETAILS_SUCCESS',
  UPDATE_USER_DETAILS_FAILURE: 'UPDATE_USER_DETAILS_FAILURE',
  UPDATE_USER_PASSWORD_START: 'UPDATE_USER_PASSWORD_START',
  UPDATE_USER_PASSWORD_SUCCESS: 'UPDATE_USER_PASSWORD_SUCCESS',
  UPDATE_USER_PASSWORD_FAILURE: 'UPDATE_USER_PASSWORD_FAILURE',
  SEND_FORGOT_PASSWORD_EMAIL_START: 'SEND_FORGOT_PASSWORD_EMAIL_START',
  SEND_FORGOT_PASSWORD_EMAIL_SUCCESS: 'SEND_FORGOT_PASSWORD_EMAIL_SUCCESS',
  SEND_FORGOT_PASSWORD_EMAIL_FAILURE: 'SEND_FORGOT_PASSWORD_EMAIL_FAILURE',
  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  RESET_FORGOT_PASSWORD_MODAL: 'RESET_FORGOT_PASSWORD_MODAL',
  SHOW_DRAWER: 'SHOW_DRAWER',
  HIDE_DRAWER: 'HIDE_DRAWER',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};

export default ManageUserInfoActionsTypes;
