const AuthActionTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT_START: 'LOG_OUT_START',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
  USER_LOGGED_IN_START: 'USER_LOGGED_IN_START',
  USER_LOGGED_IN_SUCCESS: 'USER_LOGGED_IN_SUCCESS',
  USER_LOGGED_IN_FAILURE: 'USER_LOGGED_IN_FAILURE',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
};

export default AuthActionTypes;
