const BootcampsActionTypes = {
  FETCH_BOOTCAMPS_START: 'FETCH_BOOTCAMPS_START',
  FETCH_BOOTCAMPS_SUCCESS: 'FETCH_BOOTCAMPS_SUCCESS',
  FETCH_BOOTCAMPS_FAILURE: 'FETCH_BOOTCAMPS_FAILURE',
  FETCH_BOOTCAMP_DETAILS_START: 'FETCH_BOOTCAMP_DETAILS_START',
  FETCH_BOOTCAMP_DETAILS_SUCCESS: 'FETCH_BOOTCAMP_DETAILS_SUCCESS',
  FETCH_BOOTCAMP_DETAILS_FAILURE: 'FETCH_BOOTCAMP_DETAILS_FAILURE',
  CREATE_BOOTCAMP_START: 'CREATE_BOOTCAMP_START',
  CREATE_BOOTCAMP_FAILURE: 'CREATE_BOOTCAMP_FAILURE',
  CREATE_BOOTCAMP_SUCCESS: 'CREATE_BOOTCAMP_SUCCESS',
  FETCH_USER_BOOTCAMPS_START: 'FETCH_USER_BOOTCAMPS_START',
  FETCH_USER_BOOTCAMPS_SUCCESS: 'FETCH_USER_BOOTCAMPS_SUCCESS',
  FETCH_USER_BOOTCAMPS_FAILURE: 'FETCH_USER_BOOTCAMPS_FAILURE',
  SET_AVERAGE_PRICE_FILTER: 'SET_AVERAGE_PRICE_FILTER',
  SET_CAREERS_FILTER: 'SET_CAREERS_FILTER',
  SET_OTHER_FILTERS: 'SET_OTHER_FILTERS',
  SORT_BOOTCAMPS: 'SORT_BOOTCAMPS',
  TOGGLE_AVERAGE_PRICE_FILTER: 'TOGGLE_AVERAGE_PRICE_FILTER',
};

export default BootcampsActionTypes;
