const BootcampsActionTypes = {
  FETCH_BOOTCAMPS_START: 'FETCH_BOOTCAMPS_START',
  FETCH_BOOTCAMPS_SUCCESS: 'FETCH_BOOTCAMPS_SUCCESS',
  FETCH_BOOTCAMPS_FAILURE: 'FETCH_BOOTCAMPS_FAILURE',
  FETCH_BOOTCAMP_DETAILS_START: 'FETCH_BOOTCAMP_DETAILS_START',
  FETCH_BOOTCAMP_DETAILS_SUCCESS: 'FETCH_BOOTCAMP_DETAILS_SUCCESS',
  FETCH_BOOTCAMP_DETAILS_FAILURE: 'FETCH_BOOTCAMP_DETAILS_FAILURE',
  CREATE_BOOTCAMP_START: 'CREATE_BOOTCAMP_START',
  CREATE_BOOTCAMP_FAILURE: 'CREATE_BOOTCAMP_FAILURE',
  CREATE_BOOTCAMP_SUCCESS: 'CREATE_BOOTCAMP_SUCCESS',
};

export default BootcampsActionTypes;
